app:
  # dory data directory (relative path)
  workDir: dory-data
  # dory run in which docker's directory (absolute path)
  dockerParentWorkDir: /dory-core
  # project definition version control files directory (relative path)
  defDir: dory-data/project-defs
  # project build caches directory (relative path)
  cacheDir: dory-data/caches
  # system UID dory run with
  userID: 1000
  # restful api service port
  apiPort: 9000
  # dory service name
  serviceName: dory-core
  # log output level, options: error, warning, info, debug
  logLevel: debug
  # CORS(Cross-Origin Resource Sharing) enable
  cors: true
  # jwt settings
  jwt:
    # jwt sign
    sign: {{ randAlphaNum 64 | quote }}
    # jwt expire seconds
    expireSeconds: 3600
    # jwt refresh seconds, must less than expireSeconds
    # jwt token minimum validity period equal: expireSeconds - refreshSeconds
    refreshSeconds: 60
  # user password minimum length
  passwordLength: 8
  # forget password reset token validity period hours
  resetTokenExpireHours: 24
  # initial admin user settings
  # if user not exists in openldap, it will create automatically
  # if user exists in openldap, set user to be admin
  adminUser:
    # admin user name, format like: dory-admin
    username: {{ $.dorycore.adminUser.username }}
    # admin user display name, format like: DORY-ADMIN
    name: {{ $.dorycore.adminUser.name }}
    # admin user mail
    mail: {{ $.dorycore.adminUser.mail }}
    # admin user mobile phone number
    mobile: {{ $.dorycore.adminUser.mobile }}
  # which node port range project applications can use
  nodePortRange:
    # node port range start
    nodePortRangeStart: 30100
    # node port range end
    nodePortRangeEnd: 32750
  # pipeline running status watcher settings (seconds)
  runningWatcherInterval:
    # watcher check interval (seconds)
    watcherInterval: 1
    # running status expire interval, must greater than watcherInterval (seconds)
    runningExpireInterval: 2
  # attachment maximum size (M)
  attachmentMaxSize: 4
  # crontab pipeline job check interval (seconds)
  crontabCheckInterval: 5
  # clear work space after pipeline run finish
  clearWorkspace: true
  # test report directory (relative path)
  testReportDir: dory-data/testReport
  # test report view path
  testReportUri: /assets/testReport
  # default avatar view path
  avatarDefaultUri: /avatar/default
  # default avatar full view path
  avatarDefaultUriFull: /avatar/default/avatar.png
  # user avatar directory (relative path)
  avatarDir: dory-data/avatar
  # user avatar view path
  avatarUri: /avatar/user
  # user avatar url prefix
  avatarUrlPrefix: ""
  # request timeout seconds
  requestTimeoutSeconds: 5
  # deploy check interval (seconds)
  deployCheckInterval: 5
  # deploy check maximum times
  deployCheckCountLimit: 30
  # default kubernetes environment name
  defaultEnvName: test
# smtp send mail settings
mail:
  # smtp server host
  host: {{ $.dorycore.mail.host | quote }}
  # smtp port
  port: {{ $.dorycore.mail.port }}
  # smtp user account
  username: {{ $.dorycore.mail.username | quote }}
  # smtp password
  password: {{ $.dorycore.mail.password | quote }}
  # smtp enable SSL
  ssl: {{ $.dorycore.mail.ssl }}
  # smtp sender display name
  from: {{ $.dorycore.mail.from | quote }}
  # smtp mail sender timeout settings (seconds)
  timeoutSeconds: 15
  # reset password view url in mail
  url: {{ $.viewURL }}:{{ $.dory.dorycore.port }}/resetPwd
# redis cache settings
redis:
  # redis host
  host: redis-core-dory
  # redis port
  port: 6379
  # redis password
  password: {{ $.dory.redis.password | quote }}
# mongodb settings
mongodb:
  # mongo host
  host: mongo-core-dory
  # mongo port
  port: 27017
  # mongo user name
  username: root
  # mongo password
  password: {{ $.dory.mongo.password | quote }}
  # mongo database name
  database: dorydb
# docker executor settings
docker:
  {{- if eq $.installMode "kubernetes" }}
  # if docker executors self signed certificates in kubernetes secret, these settings required
  kubernetes:
    # kubernetes api server ip address
    host: {{ $.kubernetes.host | quote }}
    # kubernetes api server port
    port: {{ $.kubernetes.port }}
    # kubernetes api server admin token
    token: {{ $.kubernetes.token | quote }}
    # docker executors self signed certificates store in which kubernetes secret
    secretTls: "{{ $.dory.docker.dockerName }}-tls"
    # docker executors self signed certificates secret in which kubernetes namespace
    namespace: {{ $.dory.namespace | quote }}
  {{- else if eq $.installMode "docker" }}
  # if docker executors self signed certificates store in directory, these settings required
  localCert:
    # ca cert path in docker executor (absolute path)
    caCrtPath: "/certs/ca.crt"
    # tls cert path in docker executor (absolute path)
    tlsCrtPath: "/certs/tls.crt"
    # tls key path in docker executor (absolute path)
    tlsKeyPath: "/certs/tls.key"
  # docker executors number, if docker executors run in docker required
  dockerNumber: {{ $.dory.docker.dockerNumber }}
  {{- end }}
  # docker executor service name
  docker: {{ $.dory.docker.dockerName | quote }}
  # docker executor port
  dockerPort: 2376
# ldap account center settings
ldap:
  # LDAP base DN setting
  baseDN: {{ $.dory.openldap.baseDN | quote}}
  # LDAP server connect url
  server: "ldap://openldap:389"
  # LDAP admin user
  adminCN: "cn=admin,{{ $.dory.openldap.baseDN }}"
  # LDAP admin password
  password: {{ $.dory.openldap.password | quote}}
# git repository settings, support gitlab and gitea
gitRepoConfigs:
  # 代码仓库类型，选项: gitlab, gitea
  - kind: {{ $.dory.gitRepo.type }}
    # 代码仓库名字标识，用于项目配置关联对应代码仓库名字，格式例如: xxx-xxx
    repoName: {{ $.dory.gitRepo.type }}-dory
    # 代码仓库外部查看url
    viewUrl: {{ $.viewURL }}:{{ $.dory.gitRepo.port }}
    # 代码仓库的地址，dory访问该仓库的地址
    {{- if eq $.dory.gitRepo.type "gitea" }}
    url: http://gitea:3000
    {{- else if eq $.dory.gitRepo.type "gitlab" }}
    url: http://gitlab
    {{- end }}
    # 代码仓库管理员账号
    username: "PLEASE_INPUT_BY_MANUAL"
    # 代码仓库管理员显示名
    name: "PLEASE_INPUT_BY_MANUAL"
    # 代码仓库管理员显示mail
    mail: "PLEASE_INPUT_BY_MANUAL"
    # 代码仓库管理员密码
    password: "PLEASE_INPUT_BY_MANUAL"
    # 代码仓库管理员token
    token: "PLEASE_INPUT_BY_MANUAL"
    # 默认tag名字
    tagDefault: "v0.1.0"
    # hotfix分支名字
    branchHotfix: hotfix
# 镜像仓库配置，支持harbor
imageRepoConfigs:
  # 镜像仓库类型，选项: harbor
  - kind: {{ $.imageRepo.type }}
    # 镜像仓库名字标识，用于项目配置关联对应代码仓库名字，格式例如: xxx-xxx
    repoName: {{ $.imageRepo.type }}-dory
    # 镜像仓库外部查看url
    viewUrl: https://{{ $.imageRepo.domainName }}
    # 镜像仓库地址，使用https
    url: {{ $.imageRepo.domainName | quote }}
    # 镜像仓库管理员账号
    username: admin
    # 镜像仓库管理员密码
    password: {{ $.imageRepo.password | quote }}
    # 镜像仓库 api访问地址，dory访问该仓库的地址
    apiUrl: https://{{ $.imageRepo.domainName }}
# 制品仓库配置，支持nexus
artifactRepoConfigs:
  # 制品仓库类型，选项: nexus
  - kind: {{ $.dory.artifactRepo.type }}
    # 制品仓库名字标识，用于项目配置关联对应代码仓库名字，格式例如: xxx-xxx
    repoName: {{ $.dory.artifactRepo.type }}-dory
    # 制品仓库外部查看url
    viewUrl: {{ $.viewURL }}:{{ $.dory.artifactRepo.port }}
    # 制品仓库地址，docker executor访问该仓库的地址（建议使用外部ip+端口）
    url: http://{{ $.hostIP }}:{{ $.dory.artifactRepo.port }}
    # 制品仓库的IP地址或者服务名，docker executor访问该仓库的地址（建议使用外部ip）
    host: {{ $.hostIP | quote }}
    # 制品仓库管理员账号
    username: admin
    # 制品仓库管理员密码
    password: "Nexus_Pwd_321"
    # 制品仓库public role名称
    publicRole: public-role
    # 制品仓库拉取dockerhub的主机地址端口，kubernetes环境拉取镜像的时候访问该仓库的地址（建议使用外部ip+端口）
    dockerHubUrl: {{ $.hostIP }}:{{ $.dory.artifactRepo.portHub }}
    # 拉取第三方开源依赖的包含公用账号密码的url，docker executor访问该仓库的地址（建议使用外部ip+端口）
    publicAccountUrl: http://public-user:public-user@{{ $.hostIP }}:{{ $.dory.artifactRepo.port }}
    # 拉取第三方开源依赖的公用账号名称
    publicUser: public-user
    # 拉取第三方开源依赖的公用账号密码
    publicPassword: public-user
    # maven第三方开源依赖的仓库相对路径
    maven: repository/maven-group-public/
    # npm第三方开源依赖的仓库相对路径
    npm: repository/npm-group-public/
    # pypi第三方开源依赖的仓库相对路径
    pip: repository/pypi-group-public/simple
    # gradle第三方开源依赖的仓库相对路径
    gradle: repository/maven-group-public/
    # go第三方开源依赖的仓库相对路径
    go: repository/go-group-public
# 公网代理服务器配置
proxy:
  # 公网代理地址
  url: http://nginx-proxy:1080

# 开通项目的时候，默认会创建对应的分支和流水线配置
defaultPipeline:
  # 分支名称
  branchName: develop
  # 是否通过push事件的webhook触发流水线
  webhookPushEvent: true
  # tag标签的后缀
  tagSuffix: "dev"
  # 默认计划任务设置
  pipelineCrons: []
  # 默认触发器设置
  pipelineTriggers: []

# 演示项目打包镜像设置
demoProjectImageSettings:
  springDemoImage: "hub/openjdk:14-jdk-alpine3.10"
  nodeDemoImage: "hub/node:13.14-alpine3.11"
  pythonDemoImage: "public/python:3.9.9-alpine3.15-dory"
  goDemoImage: "public/alpine:3.15.0-dory"
  ginDemoImage: "public/alpine:3.15.0-dory"

# 编译环境设置，对应的环境与docker镜像设置
buildDockerEnvs:
  # 开通项目的时候，是否使用制品仓库拉取第三方开源依赖
  artifactRepoDependencyPull: true
  # 默认第三方开源依赖地址，不启用制品仓库拉取第三方开源依赖情况下的依赖仓库地址设置
  defaultBuildDependency:
    # maven第三方开源依赖的仓库设置
    maven:
      # ~/.m2/settings.xml的仓库url
      - url: http://maven.aliyun.com/nexus/content/groups/public/
        # ~/.m2/settings.xml的仓库id
        id: nexus
        # ~/.m2/settings.xml的mirrorOf设置
        mirrorOf: central
    # npm第三方开源依赖的仓库设置
    npm:
      # ~/.npmrc的仓库url
      url: https://registry.npm.taobao.org
    # pypi第三方开源依赖的仓库设置
    pip:
      # ~/.pip/pip.conf的仓库url
      url: https://mirrors.aliyun.com/pypi/simple/
      # ~/.pip/pip.conf的trusted-host
      trustedHost: mirrors.aliyun.com
    # gradle第三方开源依赖的仓库设置
    gradle:
      # ~/.gradle/init.gradle的仓库url
      - url: https://maven.aliyun.com/repository/jcenter
      - url: https://maven.aliyun.com/repository/google
      - url: https://maven.aliyun.com/repository/central
      - url: https://maven.aliyun.com/repository/gradle-plugin
    # go第三方开源依赖的仓库设置
    go:
      # ~/.config/go/env的仓库url
      url: https://mirrors.aliyun.com/goproxy
  # 构建docker对应的构建用户的home目录
  dockerHomeDir: "/home/dory"
  # 构建环境设置
  dockerEnvs:
    # 构建环境的类型
    - name: maven
      # 是否把caches目录装载到容器的$HOME目录
      mountHomeDir: true
      # 是否启用外部代理服务器拉取依赖
      enableProxy: false
      # mount构建容器中非$HOME目录之外的构建依赖缓存目录
      # 例如go语言，需要装载容器中的/go/pkg作为缓存
      mountExtraCacheDirs: []
      # 执行构建命令前执行什么命令
      commandsBeforeBuild: ["pwd", "ls -al"]
      # 执行检查命令后执行什么命令
      commandsAfterCheck: []
      # 构建环境设置，环境名称和构建环境对应的镜像
      buildEnvs:
        # 构建环境名称
        - buildEnvName: maven-jdk17
          # 构建环境容器镜像所在的镜像仓库相对路径
          image: "public/maven:3.8.3-openjdk-17-dory"
        - buildEnvName: maven-jdk14
          image: "public/maven:3.6.3-jdk-14-dory"
        - buildEnvName: maven-jdk11
          image: "public/maven:3.8.4-jdk-11-dory"
        - buildEnvName: maven-jdk8
          image: "public/maven:3.8.4-jdk-8-dory"
        - buildEnvName: maven
          image: "public/maven:3.8.3-openjdk-17-dory"
    - name: npm
      mountHomeDir: false
      enableProxy: false
      mountExtraCacheDirs: []
      commandsBeforeBuild: ["pwd", "ls -al"]
      commandsAfterCheck: ["rm -rf node_modules"]
      buildEnvs:
        - buildEnvName: npm-node17
          image: "hub/node:17.0.1-alpine3.14"
        - buildEnvName: npm-node15
          image: "hub/node:15.14.0-alpine3.13"
        - buildEnvName: npm-node13
          image: "hub/node:13.14-alpine3.11"
        - buildEnvName: npm
          image: "hub/node:17.0.1-alpine3.14"
    - name: go
      mountHomeDir: false
      # 是否启用外部代理服务器拉取依赖
      enableProxy: false
      # mount构建容器中非$HOME目录之外的构建依赖缓存目录
      # 例如go语言，需要装载容器中的/go/pkg作为缓存
      mountExtraCacheDirs: ["/go/pkg"]
      # 执行构建命令前执行什么命令
      commandsBeforeBuild: ["pwd", "ls -al"]
      # 执行检查命令后执行什么命令
      commandsAfterCheck: []
      buildEnvs:
        - buildEnvName: go-1.17
          image: "public/golang:1.17.3-alpine3.15-dory"
        - buildEnvName: go-1.14
          image: "public/golang:1.14.15-alpine3.13-dory"
        - buildEnvName: go
          image: "public/golang:1.17.3-alpine3.15-dory"
      # 构建环境的类型
    - name: python
      mountHomeDir: false
      enableProxy: false
      mountExtraCacheDirs: []
      commandsBeforeBuild: ["pwd", "ls -al"]
      commandsAfterCheck: []
      buildEnvs:
        - buildEnvName: python-3.10
          image: "public/python:3.10.0-alpine3.15-dory"
        - buildEnvName: python-3.9
          image: "public/python:3.9.9-alpine3.15-dory"
        - buildEnvName: python
          image: "public/python:3.10.0-alpine3.15-dory"
    - name: gradle
      mountHomeDir: true
      enableProxy: false
      mountExtraCacheDirs: []
      commandsBeforeBuild: ["pwd", "ls -al"]
      commandsAfterCheck: []
      buildEnvs:
        - buildEnvName: gradle-jdk17
          image: "public/gradle:7.3.0-jdk17-dory"
        - buildEnvName: gradle-jdk14
          image: "public/gradle:6.7.0-jdk14-dory"
        - buildEnvName: gradle-jdk11
          image: "public/gradle:7.3.0-jdk11-dory"
        - buildEnvName: gradle-jdk8
          image: "public/gradle:7.3.0-jdk8-dory"
        - buildEnvName: gradle
          image: "public/gradle:7.3.0-jdk17-dory"
    - name: alpine
      mountHomeDir: false
      enableProxy: false
      mountExtraCacheDirs: []
      commandsBeforeBuild: ["pwd", "ls -al"]
      commandsAfterCheck: []
      buildEnvs:
        - buildEnvName: alpine-3.15
          image: "public/alpine:3.15.0-dory"
        - buildEnvName: alpine-3.14
          image: "public/alpine:3.14.3-dory"
        - buildEnvName: alpine
          image: "public/alpine:3.15.0-dory"
