version: '3'
services:
  docker:
    image: docker:20.10.7-dind
    hostname: docker
    container_name: docker
    privileged: true
    volumes:
      - ./certs:/certs
    environment:
      DOCKER_TLS_CERTDIR: ''
    command:
      - --host=tcp://0.0.0.0:2376
      - --tlsverify
      - --tlscacert=/certs/server/ca.pem
      - --tlscert=/certs/server/cert.pem
      - --tlskey=/certs/server/key.pem
    ports:
      - 2376:2376
    restart: always
