# 安装模式，选项: docker, kubernetes
# docker模式，表示把所有组件使用docker-compose的方式部署
# kubernetes模式，表示把所有组件部署在kubernetes中
{{- if eq $.mode "docker" }}
installMode: docker
{{- else if eq $.mode "kubernetes" }}
installMode: kubernetes
{{- end }}
# 所有dory组件和镜像仓库组件存放的根目录（绝对路径）
# 如果安装模式为docker，为本机的绝对路径。
# 如果安装模式为kubernetes，并且kubernetes集群存在多个节点，请保证本机挂装了共享存储(例如nfs、cephfs)，并且目录在共享存储的挂装目录下
{{- if eq $.mode "docker" }}
rootDir: "/data/docker-vols/dory-ce"
{{- else if eq $.mode "kubernetes" }}
rootDir: "/mnt/nfs/k8s-vols/dory-ce"
{{- end }}
# 主机ip地址，通过本ip地址可以访问到部署的镜像仓库和制品依赖仓库。
# 如果安装模式为docker，表示本机的ip地址，请勿使用127.0.0.1这种loopback地址。
# 如果安装模式为kubernetes，主机ip为master节点的ip地址（单master节点情况下）或者master节点的浮动ip（多master节点情况下）
{{- if eq $.mode "docker" }}
hostIP: "10.2.0.10"
{{- else if eq $.mode "kubernetes" }}
hostIP: "10.1.0.2"
{{- end }}
# 外部查看本机的url地址，请不要包含端口
viewURL: http://dory.local
# dory组件部署设置
dory:
  # dory组件所在的名字空间
  # 假如安装模式为kubernetes，表示dory组件所安装的名字空间
  # 假如安装模式为docker，表示dory组件存放的子目录
  namespace: "dory"
  {{- if eq $.mode "kubernetes" }}
  # 设置dory组件部署在哪些节点上，对应kubernetes的nodeSelector
  # 例如: "type: master"
  nodeSelector: {}
  {{- end }}
  # 代码仓库设置
  gitRepo:
    # 代码仓库类型，选项: gitea, gitlab
    # gitea 支持 arm64架构
    # gitlab 不支持 arm64架构
    type: gitea
    # 自动部署代码仓库（internal、external只能选一种部署方式）
    internal:
      # 镜像名
      image: gitea/gitea:1.16.5
      # 数据库镜像名，gitea情况下必须填写(选填)
      imageDB: mysql:8.0.20
      # 暴露的服务端口
      port: 30001
    # # 使用外部部署代码仓库，不自动部署代码仓库（internal、external只能选一种部署方式）
    # external:
    #   # 代码仓库浏览器查看url
    #   viewUrl: http://192.168.0.1:30001
    #   # 代码仓库的地址，dory访问该仓库的地址
    #   url: http://192.168.0.1:30001
    #   # 代码仓库管理员账号
    #   username: "PLEASE_INPUT_BY_MANUAL"
    #   # 代码仓库管理员显示名
    #   name: "PLEASE_INPUT_BY_MANUAL"
    #   # 代码仓库管理员显示mail
    #   mail: "PLEASE_INPUT_BY_MANUAL"
    #   # 代码仓库管理员密码
    #   password: "PLEASE_INPUT_BY_MANUAL"
    #   # 代码仓库管理员token
    #   token: "PLEASE_INPUT_BY_MANUAL"
  # 制品依赖仓库设置，不支持arm64架构
  artifactRepo:
    # 制品依赖仓库类型，选项: nexus
    type: nexus
    # 自动部署制品依赖仓库（internal、external只能选一种部署方式）
    internal:
      # 镜像名
      image: sonatype/nexus3:3.38.1
      # web服务暴露的服务端口
      port: 30003
      # dockerhub镜像代理暴露的服务端口
      portHub: 30004
      # gcr镜像代理暴露的服务端口
      portGcr: 30005
      # quay镜像代理暴露的服务端口
      portQuay: 30006
    # # 使用外部部署制品依赖仓库，不自动部署制品依赖仓库（internal、external只能选一种部署方式）
    # # 请使用docker镜像 doryengine/nexus-data-init:alpine-3.15.3 /nexus-data/nexus 目录的数据为nexus的基础数据
    # external:
    #   # 制品仓库浏览器查看url
    #   viewUrl: http://192.168.0.1:30003
    #   # 制品仓库地址，docker executor访问该仓库的地址(建议使用外部ip+端口)
    #   url: http://192.168.0.1:30003
    #   # 制品仓库的IP地址或者服务名，docker executor访问该仓库的地址(建议使用外部ip)
    #   host: 192.168.0.1
    #   # 制品仓库管理员账号
    #   username: admin
    #   # 制品仓库管理员密码
    #   password: "Nexus_Pwd_321"
    #   # 拉取第三方开源依赖的包含公用账号密码的url，docker executor访问该仓库的地址(建议使用外部ip+端口)
    #   publicAccountUrl: http://public-user:public-user@192.168.0.1:30003
    #   # 拉取第三方开源依赖的公用账号名称
    #   publicUser: public-user
    #   # 拉取第三方开源依赖的公用账号密码
    #   publicPassword: public-user
  # openldap账号中心设置，dory-core使用openldap存储用户账号
  openldap:
    # 镜像名
    image: osixia/openldap:develop-dev
    # ldapadmin镜像名
    imageAdmin: osixia/phpldapadmin:stable
    # 管理界面暴露的服务端口
    port: 30007
    # 管理员密码，为空表示自动随机生成
    password: ""
    # 账号中心域设置
    domain: "dory.local"
    # 账号中心baseDN设置
    baseDN: "dc=dory,dc=local"
  # dorycore部署设置
  dorycore:
    # dashboard暴露的服务端口
    port: 30010
  # redis缓存设置
  redis:
    # 镜像名
    image: redis:6.2.6-alpine3.15
    # 访问密码，为空表示自动随机生成
    password: ""
  # mongo数据库设置
  mongo:
    # 镜像名
    image: mongo:5.0.6-focal
    # 访问密码，为空表示自动随机生成
    password: ""
  # docker executor部署设置
  docker:
    # 镜像名
    image: docker:20.10.14-dind
    # docker executor在docker-compose或者kubernetes中部署的服务名
    dockerName: docker
    # 启动多少个docker executor实例
    dockerNumber: 2
# 镜像仓库设置，不支持arm64架构
imageRepo:
  # 镜像仓库类型，选项: harbor
  type: harbor
  # 自动部署镜像依赖仓库（internal、external只能选一种部署方式）
  internal:
    # 镜像仓库的访问域名，用于创建harbor的自签名tls证书
    domainName: harbor.dory.local
    # 镜像仓库组件所在的名字空间
    # 假如安装模式为kubernetes，表示镜像仓库组件所安装的名字空间
    # 假如安装模式为docker，表示镜像仓库组件存放的子目录
    namespace: harbor
    # 镜像仓库版本，harbor版本，支持v2.2.x - v2.4.x
    version: v2.4.2
    # 镜像仓库的管理员密码，为空表示自动随机生成
    password: ""
    {{- if eq $.mode "docker" }}
    # 镜像仓库的tls自签名证书存放的相对路径
    # 安装模式为docker情况下必须填写
    certsDir: certs
    # 镜像仓库的数据存放的相对路径
    # 安装模式为docker情况下必须填写
    dataDir: data
    {{- end }}
  # # 使用外部部署镜像仓库，不自动部署镜像仓库（internal、external只能选一种部署方式）
  # external:
  #   # 镜像仓库ip地址
  #   ip: 192.168.0.1
  #   # 镜像仓库浏览器查看url
  #   viewUrl: https://harbor.dory.local
  #   # 镜像仓库地址，使用https
  #   url: harbor.dory.local
  #   # 镜像仓库管理员账号
  #   username: admin
  #   # 镜像仓库管理员密码
  #   password: "PLEASE_INPUT_BY_MANUAL"
  #   # 镜像仓库 api访问地址，dory访问该仓库的地址
  #   apiUrl: https://harbor.dory.local
# dorycore应用设置
dorycore:
  # 默认管理员设置，自动在ldap中开通账号
  adminUser:
    # 账号名称，格式例如: dory-admin
    username: dory-admin
    # 显示名字，格式例如: DORY-管理员
    name: DORY-管理员
    # 邮箱
    mail: dory-admin@139.com
    # 手机号码
    mobile: 13812341234
  # 发送邮件设置
  mail:
    # smtp服务器地址
    host: "smtp.139.com"
    # smtp端口
    port: 25
    # smtp账号
    username: "13812341234@139.com"
    # smtp密码
    password: "13812341234"
    # smtp是否启用ssl
    ssl: false
    # 邮件发送人名字
    from: "DORY-管理员 <13812341234@139.com>"
# kubernetes环境配置，项目应用会部署在该环境
kubernetes:
  # kubernetes环境的 apiserver 地址
  host: "10.1.0.2"
  # kubernetes环境的 apiserver 端口
  port: 6443
  # kubernetes环境的 apiserver 管理权限token
  token: "xxx"

  # # 假如持久化存储使用本地存储情况下请设置，否则请删除以下配置
  # pvConfigLocal:
  #   # 本地存储路径（绝对路径）
  #   # 注意，与前边的`rootDir`设置一致
  #   localPath: "/data/k8s-vols/dory-ce"

  # 假如持久化存储使用nfs情况下请设置，否则请删除以下配置
  pvConfigNfs:
    # nfs存储路径（绝对路径）
    # 注意，这里是nfs服务器上的nfs目录，对应前边的`rootDir`设置，非本机挂装目录
    nfsPath: "/data/nfs-vols/k8s-vols/dory-ce"
    # nfs服务器地址
    nfsServer: "10.2.0.10"

  # # 假如持久化存储使用cephfs情况下请设置，否则请删除以下配置
  # pvConfigCephfs:
  #   # ceph存储路径（绝对路径）
  #   # 注意，这里是cephfs服务器上的cephfs目录，对应前边的`rootDir`设置，非本机挂装目录
  #   cephPath: "/k8s-vols/dory-ce"
  #   # ceph账号
  #   cephUser: admin
  #   # ceph秘钥
  #   cephSecret: "xxx"
  #   # ceph monitor地址
  #   cephMonitors:
  #   - "192.168.0.1:6789"
  #   - "192.168.0.2:6789"
  #   - "192.168.0.3:6789"
