# 安装模式，选项: docker, kubernetes
# docker模式，表示把所有组件使用docker-compose的方式部署
# kubernetes模式，表示把所有组件部署在kubernetes中
installMode: docker
# 所有dory组件存放的根目录，绝对路径
# 如果安装模式为kubernetes，并且kubernetes集群存在多个节点，请保证根目录在共享存储下，例如nfs、cephfs
rootDir: "/root/tmp"
# dory组件存放的子目录（相对根目录）
doryDir: "dory"
# 镜像仓库组件存放的子目录（相对根目录）
imageRepoDir: "harbor"
# 本机的ip地址，请勿使用127.0.0.1这种loopback地址
# 如果安装模式为kubernetes，主机ip为master节点的ip地址（单master节点情况下）或者master节点的浮动ip（多master节点情况下）
hostIP: "10.2.0.10"
# 外部查看本机的url地址，请不要包含端口
viewURL: http://new2.imdory.com
# dory组件部署设置
dory:
  # 代码仓库设置
  gitRepo:
    # 代码仓库类型，选项: gitea, gitlab
    type: gitea
    # 镜像名
    image: gitea/gitea:1.15.6
    # 数据库镜像名，gitea情况下必须填写
    imageDB: mysql:8.0.20
    # 暴露的服务端口
    port: 10001
  # 制品依赖仓库设置
  artifactRepo:
    # 制品依赖仓库类型，选项: nexus
    type: nexus
    # 镜像名
    image: sonatype/nexus3:3.37.0
    # web服务暴露的服务端口
    port: 10003
    # dockerhub镜像代理暴露的服务端口
    portHub: 10004
    # gcr镜像代理暴露的服务端口
    portGcr: 10005
    # quay镜像代理暴露的服务端口
    portQuay: 10006
  # openldap账号中心设置
  openldap:
    # 镜像名
    image: osixia/openldap:develop-dev
    # ldapadmin镜像名
    imageAdmin: osixia/phpldapadmin:stable-amd64
    # 管理界面暴露的服务端口
    port: 10007
    # 管理员密码，为空表示自动随机生成
    password: ""
    # 账号中心域设置
    domain: "dory.local"
    # 账号中心baseDN设置
    baseDN: "dc=dory,dc=local"
  # redis缓存设置
  redis:
    # 镜像名
    image: redis:6.2.6-alpine3.15
    # 访问密码，为空表示自动随机生成
    password: ""
  # mongo数据库设置
  mongo:
    # 镜像名
    image: mongo:4.4.10-focal
    # 访问密码，为空表示自动随机生成
    password: ""
  # docker executor部署设置
  docker:
    # 镜像名
    image: docker:20.10.11-dind
    # docker executor在docker-compose中部署的服务名
    dockerName: docker
    # 启动多少个docker executor实例
    dockerNumber: 2
  # dorycore部署设置
  dorycore:
    # dashboard暴露的服务端口
    port: 10010
# 镜像仓库设置
imageRepo:
  # 镜像仓库类型，选项: harbor
  type: harbor
  # 镜像仓库的访问域名，用于创建harbor的自签名tls证书
  domainName: harbor2.new.imdory.com
  # 镜像仓库的tls自签名证书存放的相对路径
  certsDir: certs
  # 镜像仓库的数据存放的相对路径
  dataDir: data
  # 镜像仓库的管理员密码，为空表示自动随机生成
  password: ""
  # 镜像仓库版本，harbor版本，支持v2.2.x - v2.4.x
  version: v2.4.0
# dorycore应用设置
dorycore:
  # 默认管理员设置，自动在ldap中开通账号
  adminUser:
    # 账号名称，格式例如: dory-admin
    username: dory-admin
    # 显示名字，格式例如: DORY-管理员
    name: DORY-管理员
    # 邮箱
    mail: dory-admin@139.com
    # 手机号码
    mobile: 13812341234
  # 发送邮件设置
  mail:
    # smtp服务器地址
    host: "smtp.139.com"
    # smtp端口
    port: 25
    # smtp账号
    username: "13812341234@139.com"
    # smtp密码
    password: "13812341234"
    # smtp是否启用ssl
    ssl: false
    # 邮件发送人名字
    from: "DORY-管理员 <13812341234@139.com>"
# kubernetes环境配置
kubernetes:
  # kubernetes环境的 apiserver 地址
  host: "10.1.0.2"
  # kubernetes环境的 apiserver 端口
  port: 6443
  # kubernetes环境的 apiserver token
  token: "xxx"
  # project-data-alpine pod 所在的名字空间
  namespace: "dory"

  # # 假如持久化存储使用本地存储情况下请设置，否则请删除以下配置
  # pvConfigLocal:
  #   # 本地存储路径
  #   localPath: "/data/k8s-vols"

  # 假如持久化存储使用nfs情况下请设置，否则请删除以下配置
  pvConfigNfs:
    # nfs存储路径
    nfsPath: "/data/nfs-vols/k8s-vols"
    # nfs服务器地址
    nfsServer: "10.2.0.10"

  # # 假如持久化存储使用cephfs情况下请设置，否则请删除以下配置
  # pvConfigCephfs:
  #   # ceph存储路径
  #   cephPath: "/k8s-deploy"
  #   # ceph账号
  #   cephUser: admin
  #   # ceph秘钥
  #   cephSecret: "xxx"
  #   # ceph monitor地址
  #   cephMonitors:
  #   - "192.168.0.1:6789"
  #   - "192.168.0.2:6789"
  #   - "192.168.0.3:6789"
